version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-twinkl
    ports:
      - '6900:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin-twinkl
    env_file:
      - ./.env
    ports:
      - '5090:80'
volumes:
  progresDB:
